#!/usr/bin/env bash
# Function to display information about a subdomain
display_usage() {
    echo "Usage: $0 <domain> [subdomain]"
    echo "Example: $0 holberton.online"
    echo "         $0 holberton.online web-01"
}

# Function to perform DNS lookup and display information
check_subdomain() {
    subdomain=$1
    domain=$2
    record_type="A"
    
    # Perform DNS lookup and extract relevant information
    result=$(dig +short $subdomain.$domain)
    
    # Check if the result is empty
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain is not configured for $domain"
    else
        echo "The subdomain $subdomain is a $record_type record and points to $result"
    fi
}

# Check the number of arguments
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    display_usage
    exit 1
fi

# Assign values to variables
domain=$1
subdomains=("www" "lb-01" "web-01" "web-02")

# Display information for specified subdomain or all subdomains
if [ $# -eq 1 ]; then
    for subdomain in "${subdomains[@]}"; do
        check_subdomain $subdomain $domain
    done
else
    subdomain=$2
    check_subdomain $subdomain $domain
fi
