#!/usr/bin/env bash
# Function to display information about a subdomain
display_info() {
    domain="$1"
    subdomain="$2"

    # Use dig to get information about the subdomain
    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')

    # Extract record type and destination from the result using awk
    record_type=$(echo "$result" | awk '/IN/ {print $4}')
    destination=$(echo "$result" | awk '/IN/ {print $5}')

    # Display the information
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain="$1"
subdomain="$2"

# Display information for the specified subdomain or default subdomains
if [ -z "$subdomain" ]; then
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    display_info "$domain" "$subdomain"
fi
