#!/usr/bin/env bash
# Create a custom 404 HTML page
echo "<!DOCTYPE html>" > /usr/share/nginx/html/404.html
echo "<html>" >> /usr/share/nginx/html/404.html
echo "<head>" >> /usr/share/nginx/html/404.html
echo "    <title>404 Not Found</title>" >> /usr/share/nginx/html/404.html
echo "</head>" >> /usr/share/nginx/html/404.html
echo "<body>" >> /usr/share/nginx/html/404.html
echo "    <p>Ceci n'est pas une page</p>" >> /usr/share/nginx/html/404.html
echo "</body>" >> /usr/share/nginx/html/404.html
echo "</html>" >> /usr/share/nginx/html/404.html

# Create a configuration file for the custom error page
echo "error_page 404 /404.html;" > /etc/nginx/sites-available/custom_404
echo "location = /404.html {" >> /etc/nginx/sites-available/custom_404
echo "    root /usr/share/nginx/html;" >> /etc/nginx/sites-available/custom_404
echo "    internal;" >> /etc/nginx/sites-available/custom_404
echo "}" >> /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
/etc/init.d/nginx restart
