#!/usr/bin/env bash
# Update Nginx configuration to listen on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx to apply changes
service nginx restart
