#!/usr/bin/env bash

# Update Nginx configuration to listen on port 80
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/nginx.conf
nginx -s reload
