#!/usr/bin/env bash
# Does the following:
#  create a file /var/run/myscript.pid containing the script PID
#  display "To infinity & beyond" indefinitely
#  display "I hate kill command" upon receiving a SIGTERM
#  display "Y U no love me" upon receiving SIGINT
#  delete file /var/run/mycript.pid and terminates upon
#+  receive SIGQUIT or SIGTERM

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
