#!/usr/bin/env bash
# Specify the name of the private key
private_key_name="school"

# Specify the number of bits in the key
key_bits=4096

# Specify the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f "$private_key_name" -N "$passphrase"
