#!/usr/bin/env bash
# SSH client configuration

Host *
    your_server_ip_or_hostname
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    sendEnv LANG Lc_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
